### ISSUE TITLE
Fix JavaDoc to be compliant with JDK 8 lint

### ISSUE THREAD

**Issue by lennartj** [mojohaus/aspectj-maven-plugin#1]
Currently, building site under JDK8 fails due to the stricter lint rules of current JDK 8.
Rather than simply ignoring these errors, we should fix the JavaDoc.

**Comment by bmarwell** [comment]
Fixed in https://github.com/mojohaus/aspectj-maven-plugin/commit/fced312e8c5900c655999d171f1024f25b298415
