### ISSUE TITLE
Next release should be 1.13

### ISSUE THREAD

**Issue by kriegaex** [mojohaus/aspectj-maven-plugin#101]
Currently, the POM uses `1.12.0-SNAPSHOT`. I would like to suggest switching to `1.13.0-SNAPSHOT` in order to recognise and honor the fact that Nick Wong released versions 1.12.1 and 1.12.6 already which are widely used. This project now contains changes both he and I have contributed to the project before someone started merging or replicating them here. I also tried to reflect his prior work by publishing versions like  `1.13.M3` in my fork. The world did not stop turning while this project was inactive. We are all happy that now there is some momentum in development, but I think a `1.12.0` release would cause more confusion than necessary.

WDYT, guys?

**Comment by bmarwell** [comment]
+1 for me.
Already bumped from 1.11.1 to 1.12.0 b/c of Java 8 and new aspectj version.
Honouring your version, I see no reason to not go then higher: 1.14 or even 2.0.0.
