### ISSUE TITLE
Latest release does not seems to be available in maven central yet ? 

### ISSUE THREAD

**Issue by pankajagrawal16** [mojohaus/aspectj-maven-plugin#106]
Hi, I see that there was a release 1.12.0 made yesterday https://github.com/mojohaus/aspectj-maven-plugin/releases/tag/aspectj-maven-plugin-1.12.0.

I cannot seem to find it still in maven central. https://mvnrepository.com/artifact/org.codehaus.mojo/aspectj-maven-plugin

**Comment by pankajagrawal16** [comment]
cc @olamy

**Comment by bmarwell** [comment]
Hi @pankajagrawal16 the release vote was canceled, we are re-doing a vote for 1.14.0 (renamed).
Please be aware that this is only for issues. You might want to ask questions on the google groups forums, aka our mailing list:  https://groups.google.com/g/mojohaus-dev
