### ISSUE TITLE
Plugin produces java files in project root

### ISSUE THREAD

**Issue by mark-burns** [mojohaus/aspectj-maven-plugin#14]
When using the plugin a copy of generated sources is copied to the project root (after the build I have "com/myproject/..." in the dir where the pom file resides). I've scoured the docs and search the web for answers but can't find a config that changes where these files are output. The plugin does everything else fine. Is there a way to get rid of this directory or move it into target?

**Comment by tsayen** [comment]
:+1:

**Comment by davidkarlsen** [comment]
Can you provide a stripped down project which reproduces the error? Preferably as an integration test

**Comment by mark-burns** [comment]
I'll work on a stripped down project.

**Comment by pjreed** [comment]
I think that a while back I encountered this same issue when using AspectJ during Hibernate metamodel generation; I couldn't tell whether the issue was in Hibernate or AspectJ, so I filed an issue here: https://hibernate.atlassian.net/browse/HHH-10626

And I made a stripped down project that demonstrates the problem here: https://github.com/pjreed/aspectj-metamodel-test

**Comment by davidkarlsen** [comment]
Seems to be a hibernate problem. If I comment the hibernate annotations there is no files in the root:
```
+//@Entity
+//@Table(name = "account")
```

**Comment by pjreed** [comment]
Ah, so it is.  Maybe @mark-burns's problem is unrelated, then.

**Comment by boristhecat** [comment]
I'm currently facing the same problem like @mark-burns.
The generated sources (annotation processor generated) appear at the projects root level (/root/com/project/.../GeneratedSource.java). Is there a solution or did i simply miss a config to change that behaviour? Using the maven-compiler-plugin everything is generated in the expected directories.

**Comment by davidkarlsen** [comment]
@boristhecat - if you can provide a stripped down project exercising the bug we could have a look, in @pjreed 's case it was something else causing it...

**Comment by mark-burns** [comment]
I have created a sample project that demonstrates the problem that I see. I hope that you will reopen this issue when you have a chance to look at the code. The example is found here: https://github.com/mark-burns/simple-test and just run mvn clean package. Then you should see a new folder "com" was created in the project root.

**Comment by mark-burns** [comment]
Btw, my issue sounds similar to pull request #6

**Comment by hdave** [comment]
This issue should be re-opened.  The issue with jpa-metamodel generation is not a hibernate issue.  If I set the generator directory via javac or org.bsc.maven:maven-processor-plugin they show up in the correct place.
