### ISSUE TITLE
Randomly appearing RuntimeException key not found in wovenClassFile

### ISSUE THREAD

**Issue by RevoltEnergy** [mojohaus/aspectj-maven-plugin#157]
Hi! I have a problem when sometimes my build fails with the following message:

```
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.14.0:test-compile (default) on project core: AJC compiler errors:
[ERROR] abort ABORT -- (RuntimeException) key not found in wovenClassFile
[ERROR] key not found in wovenClassFile
[ERROR] java.lang.RuntimeException: key not found in wovenClassFile
```

On the next run the problem disappears but happens again randomly. The build is a part of an automatic pipeline so this problem is really annoying, googling does not give any clue, and I cannot reproduce it ad hoc. What can you advise, maybe to check or set some parameters in the plugin config?

**Comment by kriegaex** [comment]
This error message comes from [AspectJ itself](https://github.com/eclipse/org.aspectj/blob/67b1c353a02c335074a736ebf76a49bf24eefb19/org.aspectj.matcher/src/main/java/org/aspectj/weaver/WeaverStateInfo.java#L424-L432). The possibility is that this might be unrelated to the plugin as such. Please try to create an [MCVE](https://stackoverflow.com/help/mcve) on GitHub, even if it does not always reproduce the problem. I can run it multiple times, if necessary. Then you can create an AspectJ issue. I would like to see a full, minimal project reproducing the issue. Full Maven POMs, additional error information (Maven debug log) etc. would also be helpful.

**Comment by RevoltEnergy** [comment]
@kriegaex I cannot reproduce it also, it happens very rarely but often enough to make trouble, and this is a client production code, it's almost impossible to make a MCVE, I hoped this error is something that has a specific set of known possible reasons..

**Comment by kriegaex** [comment]
MCVE != client code. You can minimise the code, strip off everything non-essential, rename all remaining packages, classes and methods and run it a thousand times on your client's Jenkins until you have the minimal project which still sometimes reproduces the problem. Sorry, I cannot debug invisible code.

**Comment by cpys** [comment]
same  problem
about 50% 


<dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjtools</artifactId>
            <version>1.9.19</version>
        </dependency>

**Comment by NicholasWalton** [comment]
AspectJ was able to resolve a similar issue: eclipse-aspectj/aspectj#245

**Comment by kriegaex** [comment]
@slachiewicz, in absence of any proof otherwise, I am assuming a build configuration problem similar to the ones discussed in https://github.com/eclipse-aspectj/aspectj/issues/245. I think, that this issue can be closed after one year without anyone having provided a reproducible example. The invalid AspectJ issue at least had one, if any of the readers here want to compare their own project with the one I fixed for the other person over there. Maybe it helps you fix your own projects.
