### ISSUE TITLE
Dependency Error AspectJ Maven Plugin Installation For com:sun:tools:jar

### ISSUE THREAD

**Issue by ihsanhaikalz** [mojohaus/aspectj-maven-plugin#16]
I would like to run the Maven project that I have on https://github.com/ihsanhaikalz/testMaven in the Eclipse 4.5 (Mars) but it gave me an error in the pom.xml as follow:

1 problem was encountered while building the effective model for
 org.codehaus.mojo:aspectj-maven-plugin:1.8 [ERROR] 
'dependencies.dependency.systemPath' for com.sun:tools:jar must specify an
 absolute path but is ${toolsjarSystemPath} @

I already installed AJDT for Eclipse 4.5 through http://download.eclipse.org/tools/ajdt/45/dev/update and when I pulled from my github the Eclipse started to download Maven plugin connectors and Maven integration for AJDT but the error is still there. For the complete question please refer to http://stackoverflow.com/questions/37994466/dependency-error-aspectj-maven-plugin-installation-for-comsuntoolsjar

**Comment by kriegaex** [comment]
I am also affected by this problem and think I just fixed it in my pull request. Would you consider releasing 1.9 soon or maybe cherry-pick my small commit onto 1.8 and push a bugfix release?

**Comment by davidkarlsen** [comment]
@kriegaex I just deployed 1.9-SNAPSHOT.
Please give it a spin and if it works out I'll release.

**Comment by kriegaex** [comment]
As I wrote weeks ago in #18, it works now. Why don't you release?

**Comment by davidkarlsen** [comment]
Sorry for the day - rolled a vote now: https://groups.google.com/forum/#!topic/mojohaus-dev/ssI-k8lx6N4

**Comment by davidkarlsen** [comment]
In central now!

**Comment by kriegaex** [comment]
Thank you very much. I just tried 1.9 and - as expected - it works.
