### ISSUE TITLE
"Pattern matching for instanceof" from Java 17 not working

### ISSUE THREAD

**Issue by jamesrdi** [mojohaus/aspectj-maven-plugin#195]
I am migrating to Java 17. But the following error is thrown:

Error: Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.15.0:compile (default) on project xxxxxx: AJC compiler errors: Error: [ERROR] error at Error: return (o instanceof ComparableVersion comparableVersion) ....... The Java feature 'Pattern Matching in instanceof Expressions' is only available with source level 16 and above Error: -> [Help 1]

I appreciate the help in advance :)

**Comment by kriegaex** [comment]
James, could you reproduce the problem with the oinformation given, if you were the one having to reproduce and debug this? Probably not. So, provide a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). Thank you.

**Comment by kriegaex** [comment]
Probably, your effective plugin configuration looks similar to this:

```xml
<configuration>
  <source>11</source>
  <target>11</target>
  <complianceLevel>17</complianceLevel>
  <showWeaveInfo>true</showWeaveInfo>
  <encoding>UTF-8</encoding>
</configuration>
```

Or maybe, you have source 11 and target 17, whatever. In any case, you need source 17.

**Comment by jamesrdi** [comment]
Yes, you are right, it is an oversight from my migration. I apologise for the unclear explanation of the problem. Thank you for your response. It really helped :)
