### ISSUE TITLE
Where to find issue http://jira.codehaus.org/browse/MASPECTJ-88 and similar?

### ISSUE THREAD

**Issue by bodrin** [mojohaus/aspectj-maven-plugin#21]
Hi,
I have this link http://jira.codehaus.org/browse/MASPECTJ-88 and it cannot be served right now.
And I have found that page so do guys know what happened with all these MASPECTJ-* issues?
Are they gone?
Thanks!

**Comment by davidkarlsen** [comment]
AFAIK none of the old issues were migrated as CodeHaus was shut down
