### ISSUE TITLE
AJC warning incorrect classpath: ... org.springframework.roo.annotations-2.0.0.BUILD-SNAPSHOT.pom

### ISSUE THREAD

**Issue by pcolot01** [mojohaus/aspectj-maven-plugin#27]
Pom dependencies like 

	<dependencyManagement>
		<dependencies>

			
			<dependency>
				<groupId>org.springframework.roo</groupId>
				<artifactId>org.springframework.roo.annotations</artifactId>
				<version>${roo.version}</version>
				<type>pom</type>
				<scope>provided</scope>
			</dependency>

are integrated in the classpath delegation as the artefact org.springframework.roo.annotations-2.0.0.BUILD-SNAPSHOT.pom associated to their dependencies. The ajc compiler is not able to able the pom dependency and is generating the warning incorrect classpath.

Pull request proposal : https://github.com/mojohaus/aspectj-maven-plugin/pull/28

**Comment by davidkarlsen** [comment]
Fixed in d9c109241dfaf4021cb45d3f77049f1fc8febb02
