### ISSUE TITLE
[WARNING] invalid Class-Path header in manifest of jar file

### ISSUE THREAD

**Issue by wjohnson000** [mojohaus/aspectj-maven-plugin#30]
I'm using `aspectj-maven-plugin`, version 1.10, to do "compile-time" weaving of my aspect data.  I get the following warning messages:
```text
[WARNING] invalid Class-Path header in manifest of jar file:
   ...\org\restlet\jee\org.restlet\2.3.0\org.restlet-2.3.0.jar
invalid Class-Path header in manifest of jar file:
    ...\org\restlet\jee\org.restlet.ext.servlet\2.3.0\org.restlet.ext.servlet-2.3.0.jar
```
This is a legitimate warning since those the JAR files do, in fact, contain manifests with an empty `Class-Path` header.

However, as far as I can tell, there is no way to disable that warning message (it's not controlled by the `<Xlint>` value).  And I couldn't figure out how to exclude those (or other JAR files) from the process.

It's not a huge deal, but in general our build/deploy system can't have errors, and shouldn't have warnings.  I need a way to get rid of that warning.

BTW -- a later version of the "org.restlet" jar has a corrected manifest file, but the associated "org.restlet.ext.server" jar does not, so the warning will persist.

**Comment by davidkarlsen** [comment]
If you can figure out how to configure ajc we can prep it in the plugin too!

**Comment by davidkarlsen** [comment]
The plugin simply delegates to ajc - so either you find an option there to apply, or it is not possible.
