### ISSUE TITLE
Unable to weave dependencies from project with POM packaging type

### ISSUE THREAD

**Issue by spoutnik-be** [mojohaus/aspectj-maven-plugin#31]
Hello,

I am looking for solution on how to correctly use this plugin to weave dependencies of a project with POM packaging type.

ArtifactHandler artifactHandler = project.getArtifact().getArtifactHandler();
if (!"java".equalsIgnoreCase(artifactHandler.getLanguage())) {
getLog().warn("Not executing aspectJ compiler as the project is not a Java classpath-capable package");
return;
}

The above code from the 'AbstractAjcCompiler' class is preventing me to weave dependencies as it explicitly prohibits the AJC compiler to be executed on POM project.

http://maven.apache.org/ref/3.1.1/maven-core/artifact-handlers.html

I was wondering if you think it is safe to skip this test in case 'forceAjcCompile' is set.

**Comment by davidkarlsen** [comment]
Try 1.11.0-SNAPSHOT
