### ISSUE TITLE
Mvn clean compile fails with $missing$ method, mvn compile works fine

### ISSUE THREAD

**Issue by KnutHR** [mojohaus/aspectj-maven-plugin#33]
My compile fails when I run mvn clean compile, but not when I run mvn compile after.

Error message:

[ERROR] The method inRangePrivate(String, BiFunction<String,T,DynamicQuery>, T, BiFunction<String,T,DynamicQuery>, T) in the type DynamicQuery is not applicable for the arguments (String, this::$missing$, Comparable, BiFunction<String,T,DynamicQuery>, Comparable)
	/opt/jenkins_home/workspace/Build/NOS3/Compile/app/src/main/java/no/tripletex/common/util/DynamicQuery.java:1031
return inRangePrivate(property,this::after, min, this::upIncludingTo, max);

Failing code:

```
public<T extends Comparable<T>> DynamicQuery inRangeInclusive(String property, T min, T max) {
		return inRangePrivate(property,this::after, min, this::upIncludingTo, max);
	}

public DynamicQuery after(String property, Comparable<?> comparable) {
		return comparable != null ? condition(property,GREATER_THAN_OR_EQUAL,comparable) : suceedCondition();
	}

public DynamicQuery upIncludingTo(String property, Comparable<?> comparable) {
		return comparable != null ? condition(property,LESS_THAN_OR_EQUAL,comparable) : suceedCondition();
	}
```

What I found interesting is that while the after method is $missing$, the very identical upIncludingTo, which is used in the same manner, is not.

I have tried aspectj versions 1.8.7-1.10.

To avoid the problem and make mvn clean compile successfull, I replace `this::after` with `(x,y) -> after(x,y)`.

**Comment by davidkarlsen** [comment]
Maybe due to code being generated after aspect is run?

**Comment by bmarwell** [comment]
@KnutHR can you give us an example project?
