### ISSUE TITLE
java 11 compiler support

### ISSUE THREAD

**Issue by matejsp** [mojohaus/aspectj-maven-plugin#41]
I am getting the following error (even when using -Daspectj.skip=true):

[INFO] --- aspectj-maven-plugin:1.11:compile (aspectj-compile) @asdfasdf ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.497 s
[INFO] Finished at: 2018-09-01T16:56:01+02:00
[INFO] Final Memory: 53M/187M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile (aspectj-compile) on project asdfasdf: Execution aspectj-compile of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11 at specified path /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/../lib/tools.jar -> [Help 1]
[ERROR]

**Comment by sauliusano** [comment]
Hi, do you have plans to support Java 11 as it was released on September 25 this year?

**Comment by RalphEng** [comment]
This is likely the same problem reported in [Issue#24 "add Java 9 support"](https://github.com/mojohaus/aspectj-maven-plugin/issues/24)

**Comment by philsttr** [comment]
Note that aspectj released [1.9.2](https://www.eclipse.org/aspectj/doc/released/README-192.html) yesterday with java 11 support.

It would be great if the aspectj-maven-plugin worked with it.

**Comment by sergiy-kozak** [comment]
Is there any work planned (for coming release?) to have this issue addressed?

**Comment by philsttr** [comment]
See #45

**Comment by bmarwell** [comment]
ITs run now all green with Java 8, 11 and 16.
