### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by juanmbellini** [mojohaus/aspectj-maven-plugin#49]
Hi, I would like to know if this project is being maintained, as I use this plugin in my projects. I see that the last commit in ```master``` is from May 31, 2018, and the last release is from January. After that, Java 10 and Java 11 where release. Even, aspjectj 1.9.2 was released, which has support for Java 11.

**Comment by nickwongdev** [comment]
I have a fork release of this project in Maven Central under com.nickwongdev. 1.12.1 works with 11, and it should be complaint with AspectJ 1.9.5 and JDK 11, 12, and 13 as soon as 1.12.6 releases to central.

**Comment by jakub-bochenski** [comment]
I think it's dead. 
Maybe somebody from Mojohaus or Snatype could at least mark it as abandoned. 

Keep up the good work @nickwongdev !

**Comment by lofidewanto** [comment]
Dear maintainers, why couldn't @nickwongdev just become a contributor for this project? It is a pitty that we have to use a different Maven plugin for AspectJ...

Keep up the good work @nickwongdev!

**Comment by bmarwell** [comment]
Hi @nickwongdev. Sorry this project has been inactive for such a long time.
If you are interested in becoming a co-maintainer, please post on the mailing lists!

Thanks and sorry for not seeing this earlier!
