### ISSUE TITLE
AspectJ maven plugin does not support the -proc ajc compiler flag to disable annotation processing

### ISSUE THREAD

**Issue by haskovec** [mojohaus/aspectj-maven-plugin#5]
This flag is still not support here. Ralph Engelmann had written a patch that he put in the old jira at codehaus.org to add this feature. It would be nice to integrate that code so I could go back to the main branch instead of using my forked version of the project.

**Comment by hdave** [comment]
Is there any kind of work-around for this?  The aspectj plugin is constantly rerunning my JPA static metamodel creation without the proper configuration.

**Comment by haskovec** [comment]
Hey Dave,

I had this issue opened back when the project was hosted at Codehaus in January. In the Jira there someone committed a 4 line fix to take care of it. Finally after it going no where and prior to this project moving here I just pulled the source code out of SVN and forked it up here with that patch. I changed all the group id's so it would be clear that this isn't the original and my goal would be to switch back to the master one, but this is a deal breaker issue for me and I haven't found anyway to advance the priority of this. So if you want you are free to use my fork with that patch in it, I am not really updating it I just had a business need to have the problem addressed: https://github.com/haskovec/aspectj-maven-plugin

My hope is that this issue gets addressed here and I can go back to using the mojohaus version, but like I say I have been waiting on this issue for 8 months so I don't have a lot of hope of getting any timely response to the issue.

**Comment by haskovec** [comment]
Thanks David!

**Comment by hdave** [comment]
I am wondering how to make use of this capability when version 1.8 is released.  Would it be as follows?

    <configuration>
        
        <compilerArgument>-proc ajc</compilerArgument>
    </configuration>

**Comment by haskovec** [comment]
I think it is going to be more like this:

`<proc>none</proc>`

**Comment by hdave** [comment]
That makes sense.  For what it's worth, the `maven-compiler-plugin` uses the following:

    <configuration>
        <compilerArgument>-proc:none</compilerArgument>
    </configuration>

I don't think there is a pressing need for consistency, however.  

If you do go with your approach, I think it should be in the `<options>` stanza under `<configuration>`.
