### ISSUE TITLE
Please add me as a contributor to this project

### ISSUE THREAD

**Issue by akovac35** [mojohaus/aspectj-maven-plugin#53]
Dear contributors/project owner.

What are the conditions for someone becoming a contributor to this project? This would include build, testing, pull request merging and plugin maintenance.

Regards,
Aleksander

**Comment by nickwongdev** [comment]
I also looked into this, but ended up maintaining a fork that I keep up to date.

**Comment by bmarwell** [comment]
Hi @akovac35 @nickwongdev 
Sorry for having this project stale. I will look into the existing Issues and PRs and work on them as best as I can.
If you are interested in contributing, please also look into the mailing lists!

Thanks!
