### ISSUE TITLE
aspectj-maven-plugin the includes tags does not  work

### ISSUE THREAD

**Issue by crazylulululu** [mojohaus/aspectj-maven-plugin#68]
I  have two aop , just want to use one of them , the  excludes is work, but the  includes does not  work, use excludes can work(It is inconvenient to add new aop  always) , use the command( mvn clean package  or  mvn clean compile)
 the following is my configuration:
![image](https://user-images.githubusercontent.com/42406448/101724347-59019900-3ae9-11eb-9ccd-7636ae95e02c.png)

`          

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>1.8.13</version>
        </dependency>
`

**Comment by crazylulululu** [comment]
@mojohaus, the includes tags does work ，or has the Functional defects（must list all the aspect class , not the aspect point ）

**Comment by qiumingzhao** [comment]
可以举个例子么

**Comment by bmarwell** [comment]
@crazylulululu can you give us a [minimal working example](https://stackoverflow.com/help/minimal-reproducible-example)?
