### ISSUE TITLE
aspectj plugin removes java 8 method parameter names information

### ISSUE THREAD

**Issue by wwwaldemar** [mojohaus/aspectj-maven-plugin#7]
The new compiler option -parameters allows to compile in the method parameter names information into the bytecode. After the aspectj processing this information goes removed.

Here ist the configuration of maven compiler plugin

```
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.3</version>
      <configuration>
        <source>1.8</source>
        <target>1.8</target>
        <compilerArgument>-parameters</compilerArgument>
      </configuration>
    </plugin>
```

And configuration of aspectj 

```
    <plugin>
      <groupId>org.codehaus.mojo</groupId>
      <artifactId>aspectj-maven-plugin</artifactId>
      <version>1.8</version>
      <executions>
        <execution>
          <goals>
            <goal>compile</goal>
            <goal>test-compile</goal>
          </goals>
        </execution>
      </executions>
      <configuration>
        <encoding>UTF-8</encoding>
        <source>1.8</source>
        <target>1.8</target>
        <complianceLevel>1.8</complianceLevel>
      </configuration>
    </plugin>
```

It will be very nice, if you fix it

**Comment by davidkarlsen** [comment]
I cannot find any explicit support for this feature in ajc: https://eclipse.org/aspectj/doc/released/devguide/ajc-ref.html  (which the plugin is using underneath).

**Comment by kriegaex** [comment]
If you look at the [AspectJ 1.8.6 release notes](https://www.eclipse.org/aspectj/doc/released/README-186.html) and follow the link to Bugzilla you will find [this ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462146) describing that `-parameters` is supported since that version. The way it is implemented is a bit weird, though, because the setting is implicitly always set and as it seems it cannot be deactivated, at least from what I see on the console and with the AspectJ Maven plugin.

Here is a console log:

```
$ cat MyClass.java
public class MyClass {
    public static void main(String[] args) {
        System.out.println(add(11, 22));
    }

    public static int add(int summand1, int summand2) {
        return summand1 + summand2;
    }
}

$ javac -source 8 -target 8 MyClass.java
$ javap -v MyClass.class | grep summand

$ javac -source 8 -target 8 -parameters MyClass.java
$ javap -v MyClass.class | grep summand
  #17 = Utf8               summand1
  #18 = Utf8               summand2
      summand1
      summand2

$ ajc -8 -cp /c/Program\ Files/Java/AspectJ/lib/aspectjrt.jar MyClass.java
$ javap -v MyClass.class | grep summand
  #35 = Utf8               summand1
  #37 = Utf8               summand2
            0       4     0 summand1   I
            0       4     1 summand2   I

$ ajc -8 -parameters -cp /c/Program\ Files/Java/AspectJ/lib/aspectjrt.jar MyClass.java
$ javap -v MyClass.class | grep summand
  #36 = Utf8               summand1
  #38 = Utf8               summand2
            0       4     0 summand1   I
            0       4     1 summand2   I
      summand1
      summand2

$ ajc -8 -g:none -cp /c/Program\ Files/Java/AspectJ/lib/aspectjrt.jar MyClass.java
$ javap -v MyClass.class | grep summand
  #35 = Utf8               summand1
  #37 = Utf8               summand2
            0       4     0 summand1   I
            0       4     1 summand2   I
```

As you can see, with `javac` the `-parameters` option is optional. With `ajc` (tested on Winsdows with AspectJ 1.8.6) no matter if I use `-parameters` or not, the parameter name info is always there, even if I use `-g:none`. As AspectJ uses the Eclipse Java Compiler (EJC) internally, I would have thought that the parameter is just passed through because EJC also [lists it as optional](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_compiler_options.htm).

Having said that, the current situation is such that you can use the parameters info from AspectJ because it will always be in the class files.

**Comment by aclement** [comment]
Not quite sure I agree with those findings... I took your MyClass.java, I then:

    ajc -1.8 -parameters MyClass.java
    javap -verbose -private MyClass
       public static void main(java.lang.String[]);
         MethodParameters:
         Name                           Flags
         args
       public static int add(int, int);
         MethodParameters:
         Name                           Flags
         summand1
         summand2

    ajc -1.8 MyClass.java
    javap -verbose -private MyClass
      There is no MethodParameters attribute on either main() or add()

Your greps seem to be searching for (or at least showing) the LocalVariableTable attribute, which is different. Appearance of the local variable table is not dictated by `-parameters`, it controls the MethodParameters attribute.

**Comment by davidkarlsen** [comment]
Also notes: https://bugs.eclipse.org/bugs/show_bug.cgi?id=479846

**Comment by andrei-ivanov** [comment]
So I'm a bit lost.
AJC seem to work fine.
Is it the aspectj-maven-plugin at fault?
Or the way we configure it? Should I run only the aspectj-maven-plugin and
disable the standard java compiler plugin?

**Comment by andrei-ivanov** [comment]
As far as I see, the examples from Andrew Clement show that AJC accepts a "-parameters" argument, and that it is not active by default.
Looking at the debug Maven ouput, I don't see it there: [DEBUG] Running : ajc -Xajruntimetarget:1.5 -1.8 -encoding UTF-8 -source 1.8 -target 1.8 -verbose -classpath ...

So, can it be added?
Or maybe something like the maven-compiler-plugin, using a generic <compilerArgument> element to just pass them down to AJC?

**Comment by andrei-ivanov** [comment]
@davidkarlsen ?

**Comment by sateeshkapu** [comment]
Is there any update on this ? I was looking for any work around available to pass this parameter.  I even looked at maven plugin source if there is any possible solution but no luck. I appreciate  any response.
Thanks

**Comment by zybreak** [comment]
I was having the same issue and created a pull-request https://github.com/mojohaus/aspectj-maven-plugin/pull/22

**Comment by kriegaex** [comment]
Oh, BTW, the milestone should probably updated to 1.10 because 1.9 was already released with one of my PRs.

**Comment by davidkarlsen** [comment]
Would it be possible to back this with some tests and documentation?

**Comment by zybreak** [comment]
@davidkarlsen I'll add documentation about the new parameter and an integration test

**Comment by zybreak** [comment]
@davidkarlsen added a little bit of documentation and a test couple of days ago, have a look and see if its alright

**Comment by davidkarlsen** [comment]
I pushed out a snapshot - please give it a spin and report back - and I can start the vote

**Comment by zybreak** [comment]
Hi David

Had a go this morning and it works like a charm.

Cheers,
Robert

**Comment by davidkarlsen** [comment]
Just released to central.
Thanks for the contribution!
