### ISSUE TITLE
java.lang.module.ResolutionException: Modules org.aspectj.weaver and org.aspectj.runtime export package org.aspectj.runtime.internal to module commons.net

### ISSUE THREAD

**Issue by sblantipodi** [mojohaus/aspectj-maven-plugin#70]
Hi all,
as title I get this error when trying to run my app...

```
 <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjrt</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
        </dependency>
----
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>1.11</version>
                <configuration>
                    <complianceLevel>${java.version}</complianceLevel>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
```

my module-info.java contains this:
    requires org.aspectj.runtime;

how can I solve it?

thanks

**Comment by bmarwell** [comment]
Hi @sblantipodi 

what is you java version and aspectj.version?
Can you please `git clone` this repo and install a local snapshot and try again to see if this has been fixed in recent commits?
Thanks!

**Comment by sblantipodi** [comment]
@bmarwell so much time passed since I opened the issue, I solved it and I don't even remeber how. Sorry.
Closing the issue.

**Comment by bmarwell** [comment]
Alright. If you ever  encounter it again, feel free to put your solution here or on the mailing lists to help others as well -- thanks! :) Glad it works for you now!
